<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'TechSource Electronics',
                'company_name' => 'TechSource Electronics Ltd.',
                'contact_person' => 'John Davidson',
                'email' => 'john.davidson@techsource.com',
                'phone' => '+1-555-0123',
                'address' => '1234 Technology Drive',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'United States',
                'postal_code' => '94105',
                'tax_id' => 'US123456789',
                'payment_terms' => 'Net 30',
                'credit_limit' => 50000.00,
                'is_active' => true,
                'notes' => 'Primary electronics supplier with excellent delivery times.',
            ],
            [
                'name' => 'Global Components Inc.',
                'company_name' => 'Global Components Incorporated',
                'contact_person' => 'Sarah Chen',
                'email' => 'sarah.chen@globalcomponents.com',
                'phone' => '+1-555-0234',
                'address' => '567 Industrial Park Way',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'United States',
                'postal_code' => '78701',
                'tax_id' => 'US234567890',
                'payment_terms' => 'Net 45',
                'credit_limit' => 75000.00,
                'is_active' => true,
                'notes' => 'Bulk supplier for electronic components and accessories.',
            ],
            [
                'name' => 'FurniCraft Manufacturers',
                'company_name' => 'FurniCraft Manufacturing Co.',
                'contact_person' => 'Michael Rodriguez',
                'email' => 'michael@furnicraft.com',
                'phone' => '+1-555-0345',
                'address' => '890 Woodwork Avenue',
                'city' => 'Portland',
                'state' => 'OR',
                'country' => 'United States',
                'postal_code' => '97201',
                'tax_id' => 'US345678901',
                'payment_terms' => 'Net 30',
                'credit_limit' => 100000.00,
                'is_active' => true,
                'notes' => 'Quality furniture manufacturer specializing in office and home furniture.',
            ],
            [
                'name' => 'Fashion Forward Wholesale',
                'company_name' => 'Fashion Forward Wholesale LLC',
                'contact_person' => 'Emma Thompson',
                'email' => 'emma@fashionforward.com',
                'phone' => '+1-555-0456',
                'address' => '123 Garment District',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'United States',
                'postal_code' => '10001',
                'tax_id' => 'US456789012',
                'payment_terms' => 'Net 15',
                'credit_limit' => 30000.00,
                'is_active' => true,
                'notes' => 'Trendy clothing and accessories supplier with seasonal collections.',
            ],
            [
                'name' => 'SportsPro Equipment',
                'company_name' => 'SportsPro Equipment & Gear',
                'contact_person' => 'David Wilson',
                'email' => 'david@sportspro.com',
                'phone' => '+1-555-0567',
                'address' => '456 Athletic Boulevard',
                'city' => 'Denver',
                'state' => 'CO',
                'country' => 'United States',
                'postal_code' => '80201',
                'tax_id' => 'US567890123',
                'payment_terms' => 'Net 30',
                'credit_limit' => 40000.00,
                'is_active' => true,
                'notes' => 'Comprehensive sports and fitness equipment supplier.',
            ],
            [
                'name' => 'GreenThumb Gardens',
                'company_name' => 'GreenThumb Garden Supply Co.',
                'contact_person' => 'Lisa Martinez',
                'email' => 'lisa@greenthumb.com',
                'phone' => '+1-555-0678',
                'address' => '789 Nursery Road',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'country' => 'United States',
                'postal_code' => '85001',
                'tax_id' => 'US678901234',
                'payment_terms' => 'Net 30',
                'credit_limit' => 25000.00,
                'is_active' => true,
                'notes' => 'Garden supplies, tools, and plant specialist.',
            ],
            [
                'name' => 'BookWorld Distributors',
                'company_name' => 'BookWorld Distribution Network',
                'contact_person' => 'Robert Johnson',
                'email' => 'robert@bookworld.com',
                'phone' => '+1-555-0789',
                'address' => '321 Publishing Street',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'United States',
                'postal_code' => '60601',
                'tax_id' => 'US789012345',
                'payment_terms' => 'Net 45',
                'credit_limit' => 60000.00,
                'is_active' => true,
                'notes' => 'Books, media, and educational materials distributor.',
            ],
            [
                'name' => 'Pacific Electronics',
                'company_name' => 'Pacific Electronics Trading Ltd.',
                'contact_person' => 'Kevin Chang',
                'email' => 'kevin@pacificelectronics.com',
                'phone' => '+1-555-0890',
                'address' => '654 Harbor View Drive',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'United States',
                'postal_code' => '98101',
                'tax_id' => 'US890123456',
                'payment_terms' => 'Net 30',
                'credit_limit' => 80000.00,
                'is_active' => true,
                'notes' => 'International electronics and mobile device supplier.',
            ],
            [
                'name' => 'HomeCare Solutions',
                'company_name' => 'HomeCare Solutions Inc.',
                'contact_person' => 'Amanda Brown',
                'email' => 'amanda@homecare.com',
                'phone' => '+1-555-0901',
                'address' => '987 Residential Way',
                'city' => 'Miami',
                'state' => 'FL',
                'country' => 'United States',
                'postal_code' => '33101',
                'tax_id' => 'US901234567',
                'payment_terms' => 'Net 30',
                'credit_limit' => 35000.00,
                'is_active' => true,
                'notes' => 'Home improvement and household goods supplier.',
            ],
            [
                'name' => 'Premier Audio Visual',
                'company_name' => 'Premier Audio Visual Systems',
                'contact_person' => 'James Taylor',
                'email' => 'james@premierav.com',
                'phone' => '+1-555-1012',
                'address' => '147 Sound Street',
                'city' => 'Nashville',
                'state' => 'TN',
                'country' => 'United States',
                'postal_code' => '37201',
                'tax_id' => 'US012345678',
                'payment_terms' => 'Net 30',
                'credit_limit' => 45000.00,
                'is_active' => true,
                'notes' => 'Professional audio and video equipment supplier.',
            ],
        ];

        foreach ($suppliers as $supplierData) {
            Supplier::create($supplierData);
        }
    }
}
